#!/data/data/com.termux/files/usr/bin/bash env

########################################
#  ALYAZOURI SETUP SCRIPT VERSIÓN : V1.0
########################################
# Dependencies: bash and curl...
########################################

# Update and upgrade
pkg up -y && pkg upgrade -y

# Switch permissive
su -c 'setenforce 0'

# Install dependencies
time apt install rsync aapt neofetch toilet ncurses-utils tsu openssl-tool ruby wget ccrypt dialog -y

# Install LOLCat via Ruby's package manager
gem install lolcat


# Fetch the CLI according to the architecture and setup
tsu -c 'wget https://raw.githubusercontent.com/Saeedjor11/Saeedyounis/master/king_jo -O ./king_jo'
tsu -c 'chmod a+x king_jo'
tsu -c ./king_jo
